
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sudverkwpahokpxxpptm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZHZlcmt3cGFob2tweHhwcHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTk1NTIsImV4cCI6MjA2MDEzNTU1Mn0.M-Pe2XJ32N3cEClaK6kthH2i6Sez1gjMXG4-XbXcDTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
